### ISSUE TITLE
Why do we need to copy a config.json file？

### ISSUE THREAD

**Issue by peteisacat** [flynnoct/chatgpt-telegram-bot#49]
Hello author, I have a question to ask. Why do we need to copy a config.json file through command during installation? Why not directly provide it in the program code? If it is provided directly, the user would have one less step during installation. I am not a programmer, just curious.Thank you for providing such an interesting project.😄

**Comment by RayCxggg** [comment]
Because the `config.json` file contains private information such as OpenAI API and Telegram tokens. We certainly don't want to expose our own keys. What's more, users may have different demands for the Bot, such as _adding more _allowed users__ or _enable Dalle_. The `config.json` file allows users to customize their own Bots complaint to their own needs.

We understand that many users are new to programming, so we try to build a comprehensive documentation which is easy to follow. Don't hesitate to try the Bot and bring up new issues when you encounter problems. Enjoy!

**Comment by RayCxggg** [comment]
I notice that issue #34 was opened by you. We are currently working on a script to help user update the config file througn command line.

**Comment by peteisacat** [comment]
@RayCxggg   Thank you for your hard work. Maybe I didn't describe the problem clearly in this question. What I mean is, why not directly provide an empty config.json file for users to fill in their own token and key, instead of manually generating config.json through the command (cp config.json.template config.json)。my english is now good ,sorry😄

**Comment by peteisacat** [comment]
> I notice that issue #34 was opened by you. We are currently working on a script to help user update the config file through command line.

@RayCxggg  cool， i got it。

**Comment by flynnoct** [comment]
Because if you messed up the config file during installation such as mis-deleting a key, you can just make a new copy from the template rather than downloading a new config file.

**Comment by peteisacat** [comment]
> Because if you messed up the config file during installation such as mis-deleting a key, you can just make a new copy from the template rather than downloading a new config file.

Thank you for your answer， i see   :)
